export const DUMMY_DATA = [
  {
    key: 1,
    title: "Driver's License",
    dueDate: "Sept. 14, 2022",
    sentTo: "Samuel A. ,Claire I, FRSC Ikeja command, Lagos",
    nextReminder: "Oct. 14, 2022",
    status: "Due",
    statusClass: "bg-blue-500 ",
  },
  {
    key: 2,
    title: "Driver's License",
    dueDate: "Sept. 14, 2022",
    sentTo: "David A. ,Claire I, FRSC Ikeja command, Lagos",
    nextReminder: "Oct. 14, 2022",
    status: "Due",
    statusClass: "bg-blue-500 ",
  },
  {
    key: 3,
    title: "Driver's License",
    dueDate: "Sept. 14, 2022",
    sentTo: "Silas A. ,Claire I, FRSC Ikeja command, Lagos",
    nextReminder: "Oct. 14, 2022",
    status: "Due",
    statusClass: "bg-blue-500 ",
  },
  {
    key: 4,
    title: "Driver's License",
    dueDate: "Sept. 14, 2022",
    sentTo: "Wole A. ,Claire I, FRSC Ikeja command, Lagos",
    nextReminder: "Oct. 14, 2022",
    status: "Due",
    statusClass: "bg-blue-500 ",
  },
  {
    key: 5,
    title: "Driver's License",
    dueDate: "Sept. 14, 2022",
    sentTo: "Ekong A. ,Claire I, FRSC Ikeja command, Lagos",
    nextReminder: "Oct. 14, 2022",
    status: "Due",
    statusClass: "bg-blue-500 ",
  },
  {
    key: 6,
    title: "Driver's License",
    dueDate: "Sept. 14, 2022",
    sentTo: "Achu A. ,Claire I, FRSC Ikeja command, Lagos",
    nextReminder: "Oct. 14, 2022",
    status: "Due",
    statusClass: "bg-blue-500 ",
  },
];

export const DUMMY_DATA2 = [
  {
    key: 1,
    title: "Reminder Accepted",
    text: "Babajide accepted to be reminded about the renewal of your Driver’s License. They will now be able to recieve an Email alert on",
    time: "1hr ago",
  },
  {
    key: 2,
    title: "Reminder Accepted",
    text: "Babajide accepted to be reminded about the renewal of your Driver’s License. They will now be able to recieve an Email alert on",
    time: "1hr ago",
  },
  {
    key: 3,
    title: "Reminder Accepted",
    text: "Babajide accepted to be reminded about the renewal of your Driver’s License. They will now be able to recieve an Email alert on",
    time: "1hr ago",
  },
  {
    key: 4,
    title: "Reminder Accepted",
    text: "Babajide accepted to be reminded about the renewal of your Driver’s License. They will now be able to recieve an Email alert on",
    time: "1hr ago",
  },
  {
    key: 5,
    title: "Reminder Accepted",
    text: "Babajide accepted to be reminded about the renewal of your Driver’s License. They will now be able to recieve an Email alert on",
    time: "1hr ago",
  },
  {
    key: 6,
    title: "Reminder Accepted",
    text: "Babajide accepted to be reminded about the renewal of your Driver’s License. They will now be able to recieve an Email alert on",
    time: "1hr ago",
  },
  {
    key:7,
    title: "Reminder Accepted",
    text: "Babajide accepted to be reminded about the renewal of your Driver’s License. They will now be able to recieve an Email alert on",
    time: "1hr ago",
  },
  {
    key: 8,
    title: "Reminder Accepted",
    text: "Babajide accepted to be reminded about the renewal of your Driver’s License. They will now be able to recieve an Email alert on",
    time: "1hr ago",
  },
  {
    key: 9,
    title: "Reminder Accepted",
    text: "Babajide accepted to be reminded about the renewal of your Driver’s License. They will now be able to recieve an Email alert on",
    time: "1hr ago",
  },
  {
    key: 10,
    title: "Reminder Accepted",
    text: "Babajide accepted to be reminded about the renewal of your Driver’s License. They will now be able to recieve an Email alert on",
    time: "1hr ago",
  },
  {
    key: 11,
    title: "Reminder Accepted",
    text: "Babajide accepted to be reminded about the renewal of your Driver’s License. They will now be able to recieve an Email alert on",
    time: "1hr ago",
  },
  {
    key: 12,
    title: "Reminder Accepted",
    text: "Babajide accepted to be reminded about the renewal of your Driver’s License. They will now be able to recieve an Email alert on",
    time: "1hr ago",
  },
  {
    key: 13,
    title: "Reminder Accepted",
    text: "Babajide accepted to be reminded about the renewal of your Driver’s License. They will now be able to recieve an Email alert on",
    time: "1hr ago",
  },
  {
    key: 14,
    title: "Reminder Accepted",
    text: "Babajide accepted to be reminded about the renewal of your Driver’s License. They will now be able to recieve an Email alert on",
    time: "1hr ago",
  },
];
